version: "2"

services:
  db:
    image: mysql
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - app.env
    volumes:
    - mysql_data:/var/lib/mysql

  app:
    build: ./
    container_name: app
    restart: always
    depends_on:
    - db
    links:
      - db
    ports:
    - "9700:9700"
    tty: true
    env_file:
      - app.env

volumes:
  mysql_data: